### ISSUE TITLE
SUN PMT reports - not displaying correctly

### ISSUE THREAD

**Issue by kreinhardt** [abyot/sun-pmt#61]
There is something weird happening with the reports. Can you take a look? I have been translating this morning but have not made any other changes. 

On the Who Does What - the column titles are not showing up and the delivery mechanism and first column are collapsed into one:
![image](https://cloud.githubusercontent.com/assets/10057077/23020972/e210da8e-f449-11e6-9308-9dbe0b6b82dd.png)

On both the geographic coverage per stakeholder and the population coverage per stakeholder - the stakeholder role dropdown is empty:
![image](https://cloud.githubusercontent.com/assets/10057077/23020956/c31fd422-f449-11e6-8e37-e3a81d562cc2.png)

**Comment by kreinhardt** [comment]
Hi @abyot is it possible to look into this soon? This is the last issue. Then I can request WFP to migrate the system to their server. Thank you!

**Comment by abyot** [comment]
Hi @kreinhardt  

I have updated the system, hope it works now. Translation of target groups should also work. 

One area, I would be happy if you can test is - in the reports make sure Delivery Mechanism and Field Implementer are not switched.

**Comment by kreinhardt** [comment]
ok - there is something going on with data entry now. The same data is showing up even when the delivery mechanism and field implementer change:
![image](https://cloud.githubusercontent.com/assets/10057077/23134004/7769bafa-f793-11e6-8011-80a1f040f8d1.png)

![image](https://cloud.githubusercontent.com/assets/10057077/23134024/86076b48-f793-11e6-90cc-c09e0fc4f100.png)

**Comment by kreinhardt** [comment]
I tested this by adding new data and it was still happening. All the other features (additional stakeholders, district specific stakeholders) seem to be working correctly.

**Comment by kreinhardt** [comment]
For the reports:

- the "who does what" is working correctly. The delivery mechanism and field implementer columns are correct. 

- It seems like the population and geographic coverage reports are mostly correct. They are displaying correctly. **However, the "field implementer" options is not appears in the dropdown list anymore.**

**Comment by kreinhardt** [comment]
regarding the translation aspect - I already removed all translations from the category and category options. Which ones can I add back in? The target groups? The delivery mechanisms?

**Comment by abyot** [comment]
ok, I have made a fix. It should be working now.

As to the translation, technically it should work for all - target group, delivery mechanisms. or the ones you just removed. Sorry that you had to redo this... if you want and if you haven't made changes since Feb 15, I can use a back up I took and restore.

**Comment by kreinhardt** [comment]
Thanks @abyot ! It looks like the data entry is working and the columns of the Who Does What are working. 

However, I still dont see the "field implementer" in the stakeholder role dropdown menu for the geographic and population coverage reports. 

I also notices the there was an extra stakeholder showing up (the last column is the french version):
![image](https://cloud.githubusercontent.com/assets/10057077/23156358/d981a684-f816-11e6-80f5-9ec199aeb9ed.png)

**Comment by abyot** [comment]
I can see the "Field Implementer" list may be a cache issue from your side?

As to the "extra" column, yes I can also see it - will check how and why it came?

**Comment by kreinhardt** [comment]
ok - great. The field implementer is appearing now. I thought I had cleared my cache. 

I will look into the extra column... its a translation of the column directly to the left of it. I will see if it has gotten into the metadata somehow and report back.

**Comment by abyot** [comment]
I think this has nothing to do with meta-data ... rather with data. See the following:

Orgunit: East
Year: 2015 
Action: "vitamin A supplementation"
Delivery mechanism: Community
Field Implementer: Action Against Hunger

There is some strange data... this shouldn't happen or I have no idea why/how it happened. I suspect it is related to the translation confusion we had, which is now solved.

**Comment by kreinhardt** [comment]
Ok - I just removed the stakeholder marked here and it seemed to take care of the extra column. 

Also, I added the translation of the categories and the category options back in but it does seem like these things are translating....

![image](https://cloud.githubusercontent.com/assets/10057077/23165432/5be38f0a-f83c-11e6-91ba-a48a75823b71.png)

**Comment by abyot** [comment]
must be your cache... every-time we make metadata change cache needs to be cleared. Also, logout and login is required if the change is about locale.

![image](https://cloud.githubusercontent.com/assets/4967749/23165542/ed906f5e-f83c-11e6-9991-32793d3be773.png)

**Comment by kreinhardt** [comment]
Ok - my cache was not set properly so it was not clearing what it needed to. Now it is. And now the translations have appears. 

One more thing - in the "who does what" report,  the delivery mechanism column and the field implementer column are switched. We had it organized so that the the table went action-target group-delivery mechanisms - field implementer -... then the other stakeholder roles. 

The only thing that is not translating is the name of stakeholders listed at catalysts, funders and responsible ministries in the reporting section. The field implementers are translating. If this is an easy fix then that is fine but if not - don't worry about it.

**Comment by abyot** [comment]
ok, I have made a fix. see below:


![image](https://cloud.githubusercontent.com/assets/4967749/23168562/e9a3ecca-f848-11e6-9bc4-30a39449304a.png)

**Comment by kreinhardt** [comment]
Great. thanks. Finishing up some translation work and I will be sending the system to WFP IT - hopefully to add the demo to the WFP server.
